import { BarcodeScanningResult, CameraView } from "expo-camera";
import { Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { colors } from "../styles/theme";

type Props = { visible: boolean; scanLocked: boolean; onBarcodeScanned: (result: BarcodeScanningResult) => void; onClose: () => void; onScanAgain: () => void; };
export function ScanGarageModal({ visible, scanLocked, onBarcodeScanned, onClose, onScanAgain }: Props) {
  return <Modal visible={visible} transparent animationType="fade"><View style={styles.modalBackdrop}><View style={styles.modalCard}><Text style={styles.modalTitle}>Scan door QR</Text><View style={styles.scannerBox}><CameraView style={styles.scanner} facing="back" barcodeScannerSettings={{ barcodeTypes: ["qr"] }} onBarcodeScanned={scanLocked ? undefined : onBarcodeScanned} /></View><Text style={styles.scanHint}>Point the camera at the Autoparkki QR code on the garage door.</Text><View style={styles.modalActions}><Pressable style={styles.cancelButton} onPress={onClose}><Text style={styles.cancelButtonText}>Cancel</Text></Pressable><Pressable style={styles.saveButton} onPress={onScanAgain}><Text style={styles.saveButtonText}>Scan again</Text></Pressable></View></View></View></Modal>;
}
const styles = StyleSheet.create({ modalBackdrop: { flex: 1, backgroundColor: "rgba(16, 24, 40, 0.45)", justifyContent: "center", padding: 24 }, modalCard: { backgroundColor: colors.card, borderRadius: 24, padding: 20 }, modalTitle: { fontSize: 24, fontWeight: "900", color: colors.text, marginBottom: 12 }, scannerBox: { height: 320, borderRadius: 20, overflow: "hidden", backgroundColor: "#101828", marginTop: 12 }, scanner: { flex: 1 }, scanHint: { marginTop: 12, fontSize: 14, color: colors.muted, lineHeight: 20 }, modalActions: { flexDirection: "row", justifyContent: "flex-end", gap: 10, marginTop: 20 }, cancelButton: { borderRadius: 14, backgroundColor: colors.surfaceSoft, paddingHorizontal: 16, paddingVertical: 12 }, cancelButtonText: { color: "#475467", fontWeight: "800" }, saveButton: { borderRadius: 14, backgroundColor: colors.green, paddingHorizontal: 16, paddingVertical: 12 }, saveButtonText: { color: "#FFFFFF", fontWeight: "900" } });
